version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8081:8080"]

  app:
    build: .
    depends_on: [postgres, redis, keycloak]
    ports: ["8080:8080"]
    volumes:
      - ./uploads:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatdb
      SPRING_DATASOURCE_USERNAME: chatuser
      SPRING_DATASOURCE_PASSWORD: chatpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      CHAT_FILE_UPLOAD_DIR: /app/uploads
