spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://auth.dev.hr.alabuga.space/realms/Alabuga
  data:
    redis:
      port: 6379
      host: redis

server:
  port: 8080

chat:
  websocket-endpoint: /ws/chat
  file-upload-dir: /app/uploads
